skip windows, I don't think it is supported or tested
Here is the Azure build error:

Created build tracker: C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-tracker-ur6f5mgk
Entered build tracker: C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-tracker-ur6f5mgk
Created temporary directory: C:\Users\VssAdministrator\AppData\Local\Temp\pip-install-mk6tkrsh
Processing c:\bld\pypmc_1663849364900\work
  Added file:///C:/bld/pypmc_1663849364900/work to build tracker 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pip-build-tracker-ur6f5mgk'
  Created temporary directory: C:\Users\VssAdministrator\AppData\Local\Temp\pip-modern-metadata-iuftv_d6
  Preparing metadata (pyproject.toml): started
  ERROR: Failed building wheel for pypmc
  Building wheel for pypmc (pyproject.toml): finished with status 'error'
Failed to build pypmc
ERROR: Could not build wheels for pypmc, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "%PREFIX%\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "%PREFIX%\lib\site-packages\pip\_internal\commands\install.py", line 431, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for pypmc, which is required to install pyproject.toml-based projects
Removed build tracker: 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pip-build-tracker-ur6f5mgk'
Traceback (most recent call last):
  File "D:\a\1\s\.ci_support\build_all.py", line 223, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "D:\a\1\s\.ci_support\build_all.py", line 120, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "D:\a\1\s\.ci_support\build_all.py", line 179, in build_folders
    conda_build.api.build([recipe], config=get_config(arch, channel_urls))
  File "C:\Miniforge\lib\site-packages\conda_build\api.py", line 186, in build
    return build_tree(
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 3091, in build_tree
    packages_from_this = build(metadata, stats,
  File "C:\Miniforge\lib\site-packages\conda_build\build.py", line 2182, in build
    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)
  File "C:\Miniforge\lib\site-packages\conda_build\windows.py", line 297, in build
    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "C:\Miniforge\lib\site-packages\conda_build\utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
[error]Cmd.exe exited with code '1'.
Finishing: Build recipe