Add LICENSE
CI breaks without adding this to the same directory...

ValueError: License file given in about/license_file
(/home/conda/staged-recipes-copy/recipes/triad/LICENSE) does not exist
in source root dir or in recipe root dir (with meta.yaml)